### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by Skb08** [Skb08/ToDoList#1]
You can modified background colour , font style and some attractive UI design.

**Comment by beatrizsmerino** [comment]
Hello @Skb08!! 😃
I want to do this task, could you please assign it to me?

I have worked before making a Todolist in Vue: [beatrizsmerino/vue-todolist](https://beatrizsmerino.github.io/vue-todolist/)

**Comment by Skb08** [comment]
Ya, Sure go ahead.

**Comment by beatrizsmerino** [comment]
> Ya, Sure go ahead.

Thank you very much, I'm going for it!
